version: '3.8'
services:
  test-db:
    image: postgres:14
    container_name: horse-pedigree-test-db
    environment:
      POSTGRES_DB: horse_pedigree_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c log_statement=all
               -c log_destination=stderr
               -c logging_collector=on
               -c log_min_duration_statement=0

volumes:
  test_postgres_data: